name: Lint Go Code

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Go Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Upload lint results (if any)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: ./golangci-lint-report.out

